# Generated by Django 3.0.8 on 2020-07-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='id',
        ),
        migrations.AlterField(
            model_name='content',
            name='path',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
