# Generated by Django 3.0.8 on 2020-07-08 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('credentials', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bio', models.CharField(max_length=180)),
                ('occupation', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('twitter_handle', models.CharField(max_length=20, null=True)),
                ('ig_handle', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
