# Generated by Django 3.0.8 on 2020-07-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_written', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=280)),
            ],
        ),
    ]
