# Generated by Django 3.0.8 on 2020-07-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_auto_20200709_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversations',
            name='time_written',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
