# Generated by Django 3.0.8 on 2020-07-15 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Potential_Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potential_matched', models.ForeignKey(default='potential_matched', on_delete=django.db.models.deletion.CASCADE, related_name='potential_matched', to=settings.AUTH_USER_MODEL)),
                ('potential_matcher', models.ForeignKey(default='potential_matcher', on_delete=django.db.models.deletion.CASCADE, related_name='potential_matcher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('potential_matcher', 'potential_matched')},
            },
        ),
    ]
