# Generated by Django 3.0.8 on 2020-07-16 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potential_matches', '0002_auto_20200715_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potentialmatches',
            name='swipedOn',
        ),
    ]
