# Generated by Django 3.0.8 on 2020-07-16 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwipedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lik22ed', models.BooleanField(default=False)),
                ('swiped', models.ForeignKey(default='swiped', on_delete=django.db.models.deletion.CASCADE, related_name='swiped', to=settings.AUTH_USER_MODEL)),
                ('swiper', models.ForeignKey(default='swiper', on_delete=django.db.models.deletion.CASCADE, related_name='swiper', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('swiper', 'swiped')},
            },
        ),
    ]
