# Generated by Django 3.0.8 on 2020-07-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiped_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swipedusers',
            name='lik22ed',
        ),
    ]
