# Generated by Django 3.0.8 on 2020-07-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiped_users', '0002_remove_swipedusers_lik22ed'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipedusers',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
